### ISSUE TITLE
SSL certificate errors

### ISSUE THREAD

**Issue by fhdk** [manjaro/pacman-mirrors#96]
Steps to reproduce

    sudo pacman -g

snip from output
```
  0.061 France         : http://manjarolinux.polymorf.fr/
   ..... France         : http://mirror.lignux.com/manjaro/Traceback (most recent call last):
  File "/usr/bin/pacman-mirrors", line 55, in <module>
    pm.run()
  File "/usr/lib/python3.6/site-packages/pacman_mirrors/pacman_mirrors.py", line 554, in run
    self.build_common_mirror_list()
  File "/usr/lib/python3.6/site-packages/pacman_mirrors/pacman_mirrors.py", line 302, in build_common_mirror_list
    worklist = self.test_mirrors(worklist)
  File "/usr/lib/python3.6/site-packages/pacman_mirrors/pacman_mirrors.py", line 525, in test_mirrors
    ssl_verify=ssl_verify)
  File "/usr/lib/python3.6/site-packages/pacman_mirrors/httpfn.py", line 119, in get_mirror_response
    urlopen(url + "state", timeout=maxwait, context=context)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 688, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 325, in match_hostname
    % (hostname, dnsnames[0]))
ssl.CertificateError: hostname 'mirror.lignux.com' doesn't match 'lignux.com'
```

**Comment by fhdk** [comment]
Commit https://github.com/manjaro/pacman-mirrors/commit/9476c8b4f604ff98f30df2d9ab7f22d3bd817b0e

**Comment by fhdk** [comment]
@philmmanjaro 
When you have the time - I request a rebuild of the master branch 4.2 dev.
[CHANGELOG](https://github.com/manjaro/pacman-mirrors/blob/master/CHANGELOG.md)
